- id: '1717335917108'
  alias: First Floor Restroom Auto
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.restroom_motion_motion
      light_target:
        device_id: 8930e125c0b90f4366ce60eceb16718e
      no_motion_wait: 1800
- id: '1717421640459'
  alias: Stair Light Auto
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 851092ee1176ca83f18c7701d8defe8f
    entity_id: ea837a7c0d3feb6cd81061c6b891956c
    domain: light
    id: stair_on
  - platform: device
    type: turned_on
    device_id: 66126f2a8c48bc52aeed8881d077b0dd
    entity_id: 39cc93262035585c5df7795212557391
    domain: light
    id: stair_on
  - platform: device
    type: turned_off
    device_id: 851092ee1176ca83f18c7701d8defe8f
    entity_id: ea837a7c0d3feb6cd81061c6b891956c
    domain: light
    id: stair_off
  - platform: device
    type: turned_off
    device_id: 66126f2a8c48bc52aeed8881d077b0dd
    entity_id: 39cc93262035585c5df7795212557391
    domain: light
    id: stair_off
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - stair_on
      sequence:
      - service: light.turn_on
        metadata: {}
        data: {}
        target:
          device_id:
          - 851092ee1176ca83f18c7701d8defe8f
          - 66126f2a8c48bc52aeed8881d077b0dd
    - conditions:
      - condition: trigger
        id:
        - stair_off
      sequence:
      - service: light.turn_off
        metadata: {}
        data: {}
        target:
          device_id:
          - 851092ee1176ca83f18c7701d8defe8f
          - 66126f2a8c48bc52aeed8881d077b0dd
  mode: single
- id: '1717503508000'
  alias: Sun Sensitive Auto Lights
  description: ''
  triggers:
  - event: sunrise
    offset: 01:00:00
    id: sunrise
    trigger: sun
  - event: sunset
    offset: -01:00:00
    id: sunset
    trigger: sun
  - entity_id:
    - binary_sensor.hallway_motion_motion_2
    - binary_sensor.hallway_motion_2_motion
    to: 'on'
    from: 'off'
    id: motion_detected
    trigger: state
  - entity_id:
    - binary_sensor.hallway_motion_motion_2
    - binary_sensor.hallway_motion_2_motion
    from: 'on'
    to: 'off'
    id: motion_clear
    trigger: state
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - sunrise
      sequence:
      - metadata: {}
        data: {}
        target:
          entity_id: light.hallway_light_light
        action: light.turn_off
      - type: turn_off
        device_id: d7b75af4498e82569ae074566943ed20
        entity_id: a8b34efd0cf993e082be9f7761683ddb
        domain: light
    - conditions:
      - condition: trigger
        id:
        - sunset
      sequence:
      - metadata: {}
        data: {}
        target:
          entity_id: light.hallway_light_light
        action: light.turn_on
      - type: turn_on
        device_id: d7b75af4498e82569ae074566943ed20
        entity_id: a8b34efd0cf993e082be9f7761683ddb
        domain: light
    - conditions:
      - condition: trigger
        id:
        - motion_detected
      sequence:
      - metadata: {}
        data: {}
        target:
          entity_id: light.hallway_light_light
        action: light.turn_on
    - conditions:
      - condition: trigger
        id:
        - motion_clear
      - condition: state
        entity_id: sun.sun
        state: above_horizon
        for:
          hours: 1
          minutes: 0
          seconds: 0
      sequence:
      - metadata: {}
        data: {}
        target:
          entity_id: light.hallway_light_light
        action: light.turn_off
  mode: single
- id: '1717740412190'
  alias: Living Room AC Toggle
  description: ''
  triggers:
  - entity_id:
    - input_boolean.living_room_ac_toggle
    from: 'off'
    to: 'on'
    id: ac_on
    trigger: state
  - entity_id:
    - input_boolean.living_room_ac_toggle
    from: 'on'
    to: 'off'
    id: ac_off
    trigger: state
  - entity_id:
    - climate.living_room_ac_living_room_ac
    from:
    to: cool
    id: on_by_climate
    trigger: state
  - entity_id:
    - climate.living_room_ac_living_room_ac
    from:
    to: 'off'
    id: off_by_climate
    trigger: state
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - ac_off
      sequence:
      - sequence:
        - data:
            hvac_mode: fan_only
          action: climate.set_hvac_mode
          target:
            device_id: 7097daddfec36630f32bd06f3cd249d3
        - metadata: {}
          data:
            fan_mode: high
          action: climate.set_fan_mode
          target:
            device_id: 7097daddfec36630f32bd06f3cd249d3
        - delay:
            hours: 0
            minutes: 30
            seconds: 0
            milliseconds: 0
        - metadata: {}
          data:
            hvac_mode: 'off'
          target:
            device_id:
            - 7097daddfec36630f32bd06f3cd249d3
          action: climate.set_hvac_mode
    - conditions:
      - condition: trigger
        id:
        - ac_on
      sequence:
      - sequence:
        - metadata: {}
          data:
            hvac_mode: cool
          action: climate.set_hvac_mode
          target:
            device_id: 7097daddfec36630f32bd06f3cd249d3
        - metadata: {}
          data:
            fan_mode: auto
          action: climate.set_fan_mode
          target:
            device_id: 7097daddfec36630f32bd06f3cd249d3
    - conditions:
      - condition: trigger
        id:
        - on_by_climate
      sequence:
      - target:
          entity_id: input_boolean.living_room_ac_toggle
        data: {}
        action: input_boolean.turn_on
    - conditions:
      - condition: trigger
        id:
        - off_by_climate
      sequence:
      - target:
          entity_id: input_boolean.living_room_ac_toggle
        data: {}
        action: input_boolean.turn_off
  mode: single
- id: '1717768528858'
  alias: Study Room AC Toggle
  description: ''
  triggers:
  - entity_id:
    - input_boolean.study_room_ac_toggle
    from: 'off'
    to: 'on'
    id: ac_on
    trigger: state
  - entity_id:
    - input_boolean.study_room_ac_toggle
    from: 'on'
    to: 'off'
    id: ac_off
    trigger: state
  - entity_id:
    - climate.study_room_ac_study_room_ac
    from:
    to: cool
    id: on_by_climate
    trigger: state
  - entity_id:
    - climate.study_room_ac_study_room_ac
    from:
    to: 'off'
    id: off_by_climate
    trigger: state
  - entity_id:
    - climate.study_room_ac_study_room_ac
    from:
    to: heat_cool
    id: on_by_climate
    trigger: state
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - ac_off
      sequence:
      - sequence:
        - data:
            hvac_mode: fan_only
          target:
            device_id: d4a36065406e8d09455e34dd1fefa483
          action: climate.set_hvac_mode
        - metadata: {}
          data:
            fan_mode: high
          target:
            device_id: d4a36065406e8d09455e34dd1fefa483
          action: climate.set_fan_mode
        - delay:
            hours: 0
            minutes: 30
            seconds: 0
            milliseconds: 0
        - metadata: {}
          data:
            hvac_mode: 'off'
          target:
            device_id: d4a36065406e8d09455e34dd1fefa483
          action: climate.set_hvac_mode
    - conditions:
      - condition: trigger
        id:
        - ac_on
      sequence:
      - sequence:
        - metadata: {}
          data:
            hvac_mode: cool
          target:
            device_id: d4a36065406e8d09455e34dd1fefa483
          action: climate.set_hvac_mode
        - metadata: {}
          data:
            fan_mode: auto
          target:
            device_id: d4a36065406e8d09455e34dd1fefa483
          action: climate.set_fan_mode
    - conditions:
      - condition: trigger
        id:
        - on_by_climate
      sequence:
      - data: {}
        target:
          entity_id: input_boolean.study_room_ac_toggle
        action: input_boolean.turn_on
    - conditions:
      - condition: trigger
        id:
        - off_by_climate
      sequence:
      - data: {}
        target:
          entity_id: input_boolean.study_room_ac_toggle
        action: input_boolean.turn_off
  mode: single
- id: '1717770075661'
  alias: Master Bedroom AC Toggle
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.master_bedroom_ac_toggle
    from: 'off'
    to: 'on'
    id: ac_on
  - platform: state
    entity_id:
    - input_boolean.master_bedroom_ac_toggle
    from: 'on'
    to: 'off'
    id: ac_off
  - platform: state
    entity_id:
    - climate.master_bedroom_ac_master_bedroom_ac
    from:
    to: cool
    id: on_by_climate
  - platform: state
    entity_id:
    - climate.master_bedroom_ac_master_bedroom_ac
    from:
    to: 'off'
    id: off_by_climate
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - ac_off
      sequence:
      - sequence:
        - service: climate.set_hvac_mode
          data:
            hvac_mode: fan_only
          target:
            device_id: db2875739677de9eed6273789ab3434b
        - service: climate.set_fan_mode
          metadata: {}
          data:
            fan_mode: high
          target:
            device_id: db2875739677de9eed6273789ab3434b
        - delay:
            hours: 0
            minutes: 30
            seconds: 0
            milliseconds: 0
        - service: climate.set_hvac_mode
          metadata: {}
          data:
            hvac_mode: 'off'
          target:
            device_id: db2875739677de9eed6273789ab3434b
    - conditions:
      - condition: trigger
        id:
        - ac_on
      sequence:
      - sequence:
        - service: climate.set_hvac_mode
          metadata: {}
          data:
            hvac_mode: cool
          target:
            device_id: db2875739677de9eed6273789ab3434b
        - service: climate.set_fan_mode
          metadata: {}
          data:
            fan_mode: auto
          target:
            device_id: db2875739677de9eed6273789ab3434b
    - conditions:
      - condition: trigger
        id:
        - on_by_climate
      sequence:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.master_bedroom_ac_toggle
    - conditions:
      - condition: trigger
        id:
        - off_by_climate
      sequence:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.master_bedroom_ac_toggle
  mode: single
- id: '1717846410007'
  alias: Kitchen Motion Activated
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.kitchen_motion_motion
      light_target:
        entity_id: light.kitchen_light_7
      no_motion_wait: 900
- id: '1730990753909'
  alias: Zigbee Restart
  description: ''
  triggers:
  - trigger: time
    at: 04:00:00
    id: reset_core
  - trigger: time
    at: 04:30:00
    id: reset_zigbee
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - reset_core
      sequence:
      - device_id: f0eb65dce680b68d7327fde1b4bc968e
        domain: button
        entity_id: e0d9c1c06142749715d36bf85f44a8ea
        type: press
      - device_id: 2f708160516acf7af87592005de93726
        domain: button
        entity_id: 4f430e12f005633a82afa91a6e4e54cc
        type: press
    - conditions:
      - condition: trigger
        id:
        - reset_zigbee
      sequence:
      - device_id: f0eb65dce680b68d7327fde1b4bc968e
        domain: button
        entity_id: ed2b80e90262cebdce41cff54ca37f19
        type: press
      - device_id: 2f708160516acf7af87592005de93726
        domain: button
        entity_id: 5a8594b0ccfe562a2fedb413873aa1a8
        type: press
  mode: single
- id: '1731815311474'
  alias: HA Restart
  description: ''
  triggers:
  - trigger: time
    at: 03:00:00
  conditions: []
  actions:
  - action: homeassistant.restart
    metadata: {}
    data: {}
  mode: single
- id: '1752200138465'
  alias: TV Auto On
  description: ''
  triggers:
  - type: turned_on
    device_id: 6ae0b15c4b1ebd3d48e9d8fa699ec3e0
    entity_id: 9320503e4f38a6e031a3714b00e991e5
    domain: remote
    trigger: device
  conditions: []
  actions:
  - type: turn_on
    device_id: 7097daddfec36630f32bd06f3cd249d3
    entity_id: 027b3523e926d7244183fd46ce73cd57
    domain: light
  mode: single
- id: '1752201172011'
  alias: TV Auto Off
  description: ''
  triggers:
  - type: turned_off
    device_id: 6ae0b15c4b1ebd3d48e9d8fa699ec3e0
    entity_id: 9320503e4f38a6e031a3714b00e991e5
    domain: remote
    trigger: device
  conditions: []
  actions:
  - type: turn_off
    device_id: 7097daddfec36630f32bd06f3cd249d3
    entity_id: 027b3523e926d7244183fd46ce73cd57
    domain: light
  mode: single
- id: '1754989046319'
  alias: Always on MB Down Lights Switch
  description: ''
  triggers:
  - type: turned_off
    device_id: cbec594961db504f782ede55617a35a7
    entity_id: 989c13381bac46d22ada803cbd9e3f09
    domain: light
    trigger: device
  conditions: []
  actions:
  - type: turn_on
    device_id: cbec594961db504f782ede55617a35a7
    entity_id: 989c13381bac46d22ada803cbd9e3f09
    domain: light
  mode: single
- id: '1762691438453'
  alias: Always ON Living Room Down Lights
  description: ''
  triggers:
  - type: turned_off
    device_id: 3aadc31f25e46b23505d730d2fbebce2
    entity_id: dd9846c86858a3b733d58b10e518d4bf
    domain: light
    trigger: device
  conditions: []
  actions:
  - type: turn_on
    device_id: 3aadc31f25e46b23505d730d2fbebce2
    entity_id: dd9846c86858a3b733d58b10e518d4bf
    domain: light
  mode: single
