- id: '1717335917108'
  alias: First Floor Restroom Auto
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.restroom_motion_motion
      light_target:
        device_id: 8930e125c0b90f4366ce60eceb16718e
      no_motion_wait: 1800
- id: '1717421640459'
  alias: Stair Light Auto
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 851092ee1176ca83f18c7701d8defe8f
    entity_id: ea837a7c0d3feb6cd81061c6b891956c
    domain: light
    id: stair_on
  - platform: device
    type: turned_on
    device_id: 66126f2a8c48bc52aeed8881d077b0dd
    entity_id: 39cc93262035585c5df7795212557391
    domain: light
    id: stair_on
  - platform: device
    type: turned_off
    device_id: 851092ee1176ca83f18c7701d8defe8f
    entity_id: ea837a7c0d3feb6cd81061c6b891956c
    domain: light
    id: stair_off
  - platform: device
    type: turned_off
    device_id: 66126f2a8c48bc52aeed8881d077b0dd
    entity_id: 39cc93262035585c5df7795212557391
    domain: light
    id: stair_off
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - stair_on
      sequence:
      - service: light.turn_on
        metadata: {}
        data: {}
        target:
          device_id:
          - 851092ee1176ca83f18c7701d8defe8f
          - 66126f2a8c48bc52aeed8881d077b0dd
    - conditions:
      - condition: trigger
        id:
        - stair_off
      sequence:
      - service: light.turn_off
        metadata: {}
        data: {}
        target:
          device_id:
          - 851092ee1176ca83f18c7701d8defe8f
          - 66126f2a8c48bc52aeed8881d077b0dd
  mode: single
- id: '1717503508000'
  alias: Sun Sensitive Auto Lights
  description: ''
  triggers:
  - event: sunrise
    offset: 01:00:00
    id: sunrise
    trigger: sun
  - event: sunset
    offset: -01:00:00
    id: sunset
    trigger: sun
  - entity_id:
    - binary_sensor.hallway_motion_motion_2
    - binary_sensor.hallway_motion_2_motion
    to: 'on'
    from: 'off'
    id: motion_detected
    trigger: state
  - entity_id:
    - binary_sensor.hallway_motion_motion_2
    - binary_sensor.hallway_motion_2_motion
    from: 'on'
    to: 'off'
    id: motion_clear
    trigger: state
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - sunrise
      sequence:
      - metadata: {}
        data: {}
        target:
          entity_id: light.hallway_light_light
        action: light.turn_off
      - type: turn_off
        device_id: d7b75af4498e82569ae074566943ed20
        entity_id: a8b34efd0cf993e082be9f7761683ddb
        domain: light
    - conditions:
      - condition: trigger
        id:
        - sunset
      sequence:
      - metadata: {}
        data: {}
        target:
          entity_id: light.hallway_light_light
        action: light.turn_on
      - type: turn_on
        device_id: d7b75af4498e82569ae074566943ed20
        entity_id: a8b34efd0cf993e082be9f7761683ddb
        domain: light
    - conditions:
      - condition: trigger
        id:
        - motion_detected
      sequence:
      - metadata: {}
        data: {}
        target:
          entity_id: light.hallway_light_light
        action: light.turn_on
    - conditions:
      - condition: trigger
        id:
        - motion_clear
      - condition: state
        entity_id: sun.sun
        state: above_horizon
        for:
          hours: 1
          minutes: 0
          seconds: 0
      sequence:
      - metadata: {}
        data: {}
        target:
          entity_id: light.hallway_light_light
        action: light.turn_off
  mode: single
- id: '1752200138465'
  alias: TV Auto On
  description: ''
  triggers:
  - type: turned_on
    device_id: 6ae0b15c4b1ebd3d48e9d8fa699ec3e0
    entity_id: 9320503e4f38a6e031a3714b00e991e5
    domain: remote
    trigger: device
  conditions: []
  actions:
  - type: turn_on
    device_id: 7097daddfec36630f32bd06f3cd249d3
    entity_id: 027b3523e926d7244183fd46ce73cd57
    domain: light
  mode: single
- id: '1752201172011'
  alias: TV Auto Off
  description: ''
  triggers:
  - type: turned_off
    device_id: 6ae0b15c4b1ebd3d48e9d8fa699ec3e0
    entity_id: 9320503e4f38a6e031a3714b00e991e5
    domain: remote
    trigger: device
  conditions: []
  actions:
  - type: turn_off
    device_id: 7097daddfec36630f32bd06f3cd249d3
    entity_id: 027b3523e926d7244183fd46ce73cd57
    domain: light
  mode: single
- id: '1754989046319'
  alias: Always on MB Down Lights Switch
  description: ''
  triggers:
  - type: turned_off
    device_id: cbec594961db504f782ede55617a35a7
    entity_id: 989c13381bac46d22ada803cbd9e3f09
    domain: light
    trigger: device
  conditions: []
  actions:
  - type: turn_on
    device_id: cbec594961db504f782ede55617a35a7
    entity_id: 989c13381bac46d22ada803cbd9e3f09
    domain: light
  mode: single
- id: '1762691438453'
  alias: Always ON Living Room Down Lights
  description: ''
  triggers:
  - type: turned_off
    device_id: 3aadc31f25e46b23505d730d2fbebce2
    entity_id: dd9846c86858a3b733d58b10e518d4bf
    domain: light
    trigger: device
  conditions: []
  actions:
  - type: turn_on
    device_id: 3aadc31f25e46b23505d730d2fbebce2
    entity_id: dd9846c86858a3b733d58b10e518d4bf
    domain: light
  mode: single
