// dashboard/src/lib/areas.ts — generated by setup-customize

export interface RoomConfig {
  id: string;
  name: string;
  floor: number;
  icon: string;
  lights: string[];
  occupancySensor?: string;
  zoneOccupancy?: string[];
  temperatureSensor?: string;
  humiditySensor?: string;
  co2Sensor?: string;
  illuminanceSensor?: string;
  noiseSensor?: string;
  pressureSensor?: string;
  aqiSensor?: string;
  temperatureRate?: string;
  covers?: string[];
  contactSensors?: { entity: string; label: string; type?: "door" | "window" }[];
  climate?: string[];
  effectiveTarget?: string;
  mediaPlayers?: string[];
}

export const ROOMS: RoomConfig[] = [
  {
    id: "living_room",
    name: "Living Room",
    floor: 1,
    icon: "mdi:sofa",
    lights: [
      "light.master_living_room",
      "light.living_room_down_lights",
      "light.leftrightlights_light",
      "light.leftrightlights_light_2",
      "light.center_light_4",
      "light.center_light_6",
    ],
    occupancySensor: "binary_sensor.restroom_motion_motion",
    temperatureSensor: "sensor.dht_temperature",
    humiditySensor: "sensor.dht_humidity",
    climate: [
      "climate.living_room_ac_living_room_ac",
      "climate.mitsubishi_ac_5138b5_mitsubishi_ac",
    ],
    mediaPlayers: [
      "media_player.sweety_tv",
      "media_player.xiaomi_tv_box",
    ],
  },
  {
    id: "master_bedroom",
    name: "Master Bedroom",
    floor: 2,
    icon: "mdi:bed-king",
    lights: [
      "light.master_bedroom_lights",
      "light.mb_down_light_group",
      "light.mb_second_light_light",
      "light.mibedsidelamp2_ab61",
    ],
    temperatureSensor: "sensor.master_bedroom_ac_temperature",
    humiditySensor: "sensor.master_bedroom_ac_humidity",
    climate: ["climate.master_bedroom_ac_master_bedroom_ac"],
    mediaPlayers: ["media_player.atom_echo_master_bedroom"],
  },
  {
    id: "study_room",
    name: "Study Room",
    floor: 2,
    icon: "mdi:desk",
    lights: [
      "light.study_room_lights",
      "light.ambient_leds",
      "light.study_light",
    ],
    temperatureSensor: "sensor.temperature",
    humiditySensor: "sensor.humidity",
    climate: ["climate.study_room_ac_study_room_ac"],
    mediaPlayers: ["media_player.atom_echo_study_room"],
  },
  {
    id: "kitchen",
    name: "Kitchen",
    floor: 1,
    icon: "mdi:pot-steam",
    lights: [
      "light.kitchen_light_7",
      "light.kitchen_light_8",
      "light.kitchen_light_9",
    ],
    occupancySensor: "binary_sensor.kitchen_motion_motion",
  },
];

// Maps HA person entity name (lowercase) → pinned room id
export const USER_ROOM_MAP: Record<string, string> = {};
