// dashboard/src/lib/entities.ts — generated by setup-customize
// Edit this file to update entity mappings. Re-run setup-customize to regenerate.

// ── Config object type definitions ─────────────────────────────────────────

export interface HeaderConfig {
  climateMode: string;
  outdoorTemp: string;
  weather: string;
  persons: { id: string; name: string }[];
}

export interface ContextConfig {
  timeOfDay: string;
  boilerEntity: string;
  solarPower: string;
  loadPower: string;
  chargerPower: string;
  chargerPowerOffered: string;
  chargerStatus: string;
  evBattery: string;
  evCharging: string;
}

export interface QuickActionsConfig {
  timeOfDay: string;
  projector: string;
  nightMode: string;
  movieMode: string;
  workMode: string;
  awayMode: string;
}

export interface ActiveAutomationsConfig {
  nightMode: string;
  movieMode: string;
  workMode: string;
  awayMode: string;
  lrAc: string;
  brAc: string;
  sparePower: string;
  chargerStatus: string;
  chargerPower: string;
  chargerPowerOffered: string;
  evCharging: string;
}

export interface VacuumConfig {
  vacuum: string;
  battery: string;
  movement: string;
  cleaningMode: string;
  turboMode: string;
  lamp: string;
  power: string;
}

export interface CameraConfig {
  id: string;
  label?: string;
  entity: string;
  batterySensor?: string;
  wifiSensor?: string;
  chargingSensor?: string;
  eventImage?: string;
  personSensor?: string;
}

interface ScheduleGroup {
  title: string;
  items: { entity: string; label: string; icon: string }[];
}
export type ScheduleEditorConfig = ScheduleGroup[];

export interface TempPresetsConfig {
  climateModeEntity: string;
  coolingPresets: { entity: string; label: string; icon: string; min: number; max: number }[];
  heatingPresets: { entity: string; label: string; icon: string; min: number; max: number }[];
}

interface ZoneConfig {
  name: string;
  sensorId: string;
  targetId: string;
  overrideBoolean: string;
  overrideTarget: string;
  acEntity: string;
}

// ── Modes ──────────────────────────────────────────────────────────────────
export const NIGHT_MODE = "input_boolean.night_mode";
export const MOVIE_MODE = "input_boolean.movie_mode";
// Placeholder — add input_boolean.work_mode / away_mode when you set up those domains
export const WORK_MODE = "";
export const AWAY_MODE = "";
export const CLIMATE_MODE = "";          // no global climate mode selector in this setup
export const NEXT_CLIMATE_TRANSITION = ""; // no climate scheduling in this setup

// ── People ─────────────────────────────────────────────────────────────────
export const PERSONS: string[] = [
  "person.nayot_kurukitkoson",
  "person.jittima_charoenpanich",
];

// ── Motion light helpers ────────────────────────────────────────────────────
export const TIMEOUT_MOTION_NORMAL       = "input_number.timeout_motion_normal";
export const TIMEOUT_MOTION_NORMAL_LONG  = "input_number.timeout_motion_normal_long";
export const TIMEOUT_MOTION_NIGHT        = "input_number.timeout_motion_night";
export const TIMEOUT_MOTION_NIGHT_SHORT  = "input_number.timeout_motion_night_short";
export const TIMEOUT_MOTION_MOVIE        = "input_number.timeout_motion_movie";
export const TRANSITION_ON               = "input_number.transition_on";
export const TRANSITION_OFF              = "input_number.transition_off";

// ── Energy & power ─────────────────────────────────────────────────────────
export const SOLAR_POWER = "";
export const DISHWASHER_STATUS        = "";
export const DISHWASHER_TIME_REMAINING = "";

// ── Security ───────────────────────────────────────────────────────────────
export const CAMERAS: CameraConfig[] = [];
export const GATE_LOCK        = "";
export const NIGHT_ALERTS     = "";
export const DOORBELL_RINGING = "";
export const SNAPSHOT_SAVE_CAMERA = "";

// ── System health ──────────────────────────────────────────────────────────
export const SYSTEM_CPU       = "";
export const SYSTEM_RAM       = "";
export const SYSTEM_DISK      = "";
export const SYSTEM_LAST_BOOT = "";

// ── Weather ────────────────────────────────────────────────────────────────
export const WEATHER = "weather.forecast_home";

// ── Climate zone map ───────────────────────────────────────────────────────
// This setup uses individual AC units per room — no zone controller.
export const ROOM_ZONE_MAP: Record<string, ZoneConfig> = {};

// ── Config objects ─────────────────────────────────────────────────────────

export const HEADER_CONFIG: HeaderConfig = {
  climateMode: CLIMATE_MODE,
  outdoorTemp: "sensor.dht_temperature",
  weather:     WEATHER,
  persons: [
    { id: "person.nayot_kurukitkoson",   name: "Nayot" },
    { id: "person.jittima_charoenpanich", name: "Jittima" },
  ],
};

export const CONTEXT_CONFIG: ContextConfig = {
  timeOfDay:          "",
  boilerEntity:       "",
  solarPower:         SOLAR_POWER,
  loadPower:          "sensor.energy_monitor_pzem_004t_v3_power",
  chargerPower:       "",
  chargerPowerOffered: "",
  chargerStatus:      "",
  evBattery:          "",
  evCharging:         "",
};

export const QUICK_ACTIONS_CONFIG: QuickActionsConfig = {
  timeOfDay: "",
  projector: "",
  nightMode: NIGHT_MODE,
  movieMode: MOVIE_MODE,
  workMode:  WORK_MODE,
  awayMode:  AWAY_MODE,
};

export const ACTIVE_AUTOMATIONS_CONFIG: ActiveAutomationsConfig = {
  nightMode: NIGHT_MODE,
  movieMode: MOVIE_MODE,
  workMode:  WORK_MODE,
  awayMode:  AWAY_MODE,
  lrAc:   "climate.living_room_ac_living_room_ac",
  brAc:   "climate.master_bedroom_ac_master_bedroom_ac",
  sparePower:          SOLAR_POWER,
  chargerStatus:       "",
  chargerPower:        "",
  chargerPowerOffered: "",
  evCharging:          "",
};

// No vacuum in this setup
export const VACUUM_CONFIG: VacuumConfig = {
  vacuum:      "",
  battery:     "",
  movement:    "",
  cleaningMode: "",
  turboMode:   "",
  lamp:        "",
  power:       "",
};

export const SCHEDULE_EDITOR_CONFIG: ScheduleEditorConfig = [];

export const TEMP_PRESETS_CONFIG: TempPresetsConfig = {
  climateModeEntity: CLIMATE_MODE,
  coolingPresets: [],
  heatingPresets: [],
};
